name: Deploy application
on: [repository_dispatch, push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "hello, world"
      - name: Dump event
        run: jq . $GITHUB_EVENT_PATH
